/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.helpdesk_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author Lenovo
 */
public class Mentor_Allocation extends javax.swing.JFrame {

    /**
     * Creates new form Mentor_Allocation
     */
    public Mentor_Allocation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        RegId = new javax.swing.JTextField();
        MentorName = new javax.swing.JComboBox<>();
        Phno = new javax.swing.JTextField();
        GenderName = new javax.swing.JComboBox<>();
        nam = new javax.swing.JTextField();
        yearOfStudy = new javax.swing.JComboBox<>();
        MentBack = new javax.swing.JButton();
        MentClear = new javax.swing.JButton();
        depName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MentUpdate = new javax.swing.JButton();
        MentReg = new javax.swing.JButton();
        MentSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jComboBox2.setBackground(new java.awt.Color(51, 0, 51));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        RegId.setBackground(new java.awt.Color(51, 0, 51));
        RegId.setForeground(new java.awt.Color(255, 255, 255));

        MentorName.setBackground(new java.awt.Color(51, 0, 51));
        MentorName.setForeground(new java.awt.Color(255, 255, 255));
        MentorName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr Shailesh Sivan", "Dr Madhu S Nair", "Dr Bijoy Antony Jose", "Dr Philip Samuvel" }));
        MentorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentorNameActionPerformed(evt);
            }
        });

        Phno.setBackground(new java.awt.Color(51, 0, 51));
        Phno.setForeground(new java.awt.Color(255, 255, 255));
        Phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhnoActionPerformed(evt);
            }
        });

        GenderName.setBackground(new java.awt.Color(51, 0, 51));
        GenderName.setForeground(new java.awt.Color(255, 255, 255));
        GenderName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        GenderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderNameActionPerformed(evt);
            }
        });

        nam.setBackground(new java.awt.Color(51, 0, 51));
        nam.setForeground(new java.awt.Color(255, 255, 255));
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        yearOfStudy.setBackground(new java.awt.Color(51, 0, 51));
        yearOfStudy.setForeground(new java.awt.Color(255, 255, 255));
        yearOfStudy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ", "2", "3", "4", "5" }));
        yearOfStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearOfStudyActionPerformed(evt);
            }
        });

        MentBack.setBackground(new java.awt.Color(255, 255, 204));
        MentBack.setForeground(new java.awt.Color(51, 0, 51));
        MentBack.setText("Back");
        MentBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentBackMouseClicked(evt);
            }
        });
        MentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentBackActionPerformed(evt);
            }
        });

        MentClear.setBackground(new java.awt.Color(255, 255, 204));
        MentClear.setForeground(new java.awt.Color(51, 0, 51));
        MentClear.setText("Clear");
        MentClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentClearMouseClicked(evt);
            }
        });
        MentClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentClearActionPerformed(evt);
            }
        });

        depName.setBackground(new java.awt.Color(51, 0, 51));
        depName.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MentClear)
                        .addGap(31, 31, 31)
                        .addComponent(MentBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(GenderName, 0, 149, Short.MAX_VALUE)
                            .addComponent(RegId)
                            .addComponent(MentorName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Phno)
                            .addComponent(yearOfStudy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(RegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(MentorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(GenderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(yearOfStudy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MentClear)
                    .addComponent(MentBack))
                .addGap(147, 147, 147))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mentor Allocation");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register id");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mentor");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Year Of Study");

        MentUpdate.setBackground(new java.awt.Color(255, 255, 204));
        MentUpdate.setForeground(new java.awt.Color(51, 0, 51));
        MentUpdate.setText("Update");
        MentUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentUpdateMouseClicked(evt);
            }
        });
        MentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentUpdateActionPerformed(evt);
            }
        });

        MentReg.setBackground(new java.awt.Color(255, 255, 204));
        MentReg.setForeground(new java.awt.Color(51, 0, 51));
        MentReg.setText("Register");
        MentReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentRegMouseClicked(evt);
            }
        });
        MentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentRegActionPerformed(evt);
            }
        });

        MentSearch.setBackground(new java.awt.Color(255, 255, 204));
        MentSearch.setForeground(new java.awt.Color(51, 0, 51));
        MentSearch.setText("Search");
        MentSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentSearchMouseClicked(evt);
            }
        });
        MentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentSearchActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\reg1.jpeg")); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(MentReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(MentSearch)
                .addGap(45, 45, 45)
                .addComponent(MentUpdate)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MentUpdate)
                    .addComponent(MentSearch)
                    .addComponent(MentReg))
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void MentorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MentorNameActionPerformed

    private void GenderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderNameActionPerformed

    private void yearOfStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearOfStudyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearOfStudyActionPerformed

    private void MentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MentRegActionPerformed

    private void MentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MentUpdateActionPerformed

    private void MentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MentBackActionPerformed

    private void MentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MentSearchActionPerformed

    private void MentClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MentClearActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    private void PhnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhnoActionPerformed

    private void MentRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentRegMouseClicked
    String name =RegId.getText() ;
    String Department=depName.getText();
    String Mentor  =MentorName.getSelectedItem() .toString();
    String Gender =GenderName.getSelectedItem() .toString();
    String Name =nam.getText() ;
    String Phone =Phno.getText() ;
    String Year  =yearOfStudy.getSelectedItem() .toString();
    
    
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/java_app","root","root");
            Statement stml=con.createStatement();
            String sql = "insert into mentor_login values('"+name+"','"+Department+"','"+Mentor+"','"+Gender+"','"+Name+"','"+Phone+"','"+Year+"')";
            stml.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Register  successfully");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(this,e.getMessage());        // TODO add your handling code here:
    }//GEN-LAST:event_MentRegMouseClicked
    }
    private void MentUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentUpdateMouseClicked

    
    PreparedStatement ps;
    String name1 =RegId.getText() ;
    String Department2=depName.getText();
    String Mentor3  =MentorName.getSelectedItem() .toString();
    String Gender4 =GenderName.getSelectedItem() .toString();
    String Name5 =nam.getText() ;
    String Phone6 =Phno.getText() ;
    String Year7  =yearOfStudy.getSelectedItem() .toString();
    
    
   try{
         
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/java_app","root","root");
    Statement stml=con.createStatement();
    String sql = "UPDATE mentor_login SET Department='"+Department2+"',Mentor='"+Mentor3+"',Gender='"+Gender4+"',Name='"+Name5+"',PhoneNumber='"+Phone6+"',YearOfStudy='"+Year7+"'where Registerid='"+name1+"'";
    ps=con.prepareStatement(sql);
    ps.execute();
    stml.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"Search successfully");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(this,e.getMessage());        // TODO add your handling code here:
    }                                    
        
    }//GEN-LAST:event_MentUpdateMouseClicked

    private void MentClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentClearMouseClicked
    String name3 =RegId.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_app","root","root");
            Statement stm = con.createStatement();
           
            String sql = "DELETE FROM mentor_login WHERE Registerid='"+name3+"'";
            stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Deleted Successfully");

        }
        catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MentClearMouseClicked

    private void MentSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentSearchMouseClicked
    String name2 = RegId.getText();
    String Department3 = depName.getText();
    String Mentor4 = MentorName.getSelectedItem().toString();
    String Gender5 = GenderName.getSelectedItem().toString();
    String Name6 = nam.getText();
    String Phone7= Phno.getText();
    String Year8=yearOfStudy.getSelectedItem().toString();
    PreparedStatement ps;
    ResultSet rs;
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/java_app","root","root");
            String querysql = "select * from mentor_login where Registerid='"+name2+"'";
            ps = con.prepareStatement(querysql);
            rs = ps.executeQuery();
            
            if(rs.next()){
                name2 = rs.getString("Registerid");
                RegId.setText(name2);
                Department3 = rs.getString("Department");
                depName.setText(Department3);
                MentorName.setSelectedItem(rs.getString("Mentor"));
                GenderName.setSelectedItem(rs.getString("Gender"));
                Name6 = rs.getString("Name");
                nam.setText(Name6);
                Phone7=rs.getString("PhoneNumber");
                Phno.setText(Phone7);
                yearOfStudy.setSelectedItem(rs.getString("YearOfStudy"));
                
                
                
                
                
                
                
                
                
            }
            //JOptionPane.showMessageDialog(null,"Updated Successfully");
        }
        catch(Exception e){
            //System.out.println(e);
            JOptionPane.showMessageDialog(this,e.getMessage());
        
    }                     
        
        
     
    
  

                                          
        // TODO add your handling code here:
    }//GEN-LAST:event_MentSearchMouseClicked

    private void MentBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentBackMouseClicked
      homepage h=new homepage();
     h.setVisible(true);
     this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_MentBackMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mentor_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mentor_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mentor_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mentor_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mentor_Allocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GenderName;
    private javax.swing.JButton MentBack;
    private javax.swing.JButton MentClear;
    private javax.swing.JButton MentReg;
    private javax.swing.JButton MentSearch;
    private javax.swing.JButton MentUpdate;
    private javax.swing.JComboBox<String> MentorName;
    private javax.swing.JTextField Phno;
    private javax.swing.JTextField RegId;
    private javax.swing.JTextField depName;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nam;
    private javax.swing.JComboBox<String> yearOfStudy;
    // End of variables declaration//GEN-END:variables
}
