/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.data.db;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    static ApplicationMainUI applicationMainUI = null;

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        applicationMainUI = new ApplicationMainUI();
        applicationMainUI.setSize(600, 600);
        applicationMainUI.setVisible(true);
    }
}
